server:
  port: 8081
logging:
  level:
    org:
      hibernate:
        SQL: DEBUG
        type: TRACE
#spring:
#  datasource:
#    driver-class-name: org.postgresql.Driver
#    url: jdbc:postgresql://localhost:5432/raze
#    username: postgres
#    password: PostgressAdmin
#  jpa:
#    database: postgresql
#    hibernate:
#      ddl-auto: update
#    show-sql: true
#    properties:
#      hibernate:
#        dialect: org.hibernate.dialect.PostgreSQLDialect
spring:
  datasource:
    url: postgres://jblkknniowgilz:66a65a3dc0699aa679d3e48b1747e4f527ea5c6d3f96bf7e319b6b680e1114cf@ec2-54-91-223-99.compute-1.amazonaws.com:5432/ddoepqol2dn90a
    username: jblkknniowgilz
    password: 66a65a3dc0699aa679d3e48b1747e4f527ea5c6d3f96bf7e319b6b680e1114cf
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQL10Dialect
